### ISSUE TITLE
Add new entry to C-5 for SMAP

### ISSUE THREAD

**Issue by SimonElliottEUM** [wmo-im/CCT#103]
# Summary and purpose

EUMETSAT proposes a new entry in Common Code Tables C-5.

# Action proposed

The team is kindly asked to validate the proposed new entry to be included within the next update to the WMO Manual on Codes.

# Discussions

The SMAP data created by NASA and passed from NOAA's PDA system to EUMETSAT, where they are formatted in BUFR by EUMETSAT and passed to ECMWF only. An identifier for the SMAP satellite is required (noting that the value 789 has been used on an _ad hoc_ basis for many years, and remains available)

# Detailed proposal

Common Code Table C-5  
SMAP  
Code figure for I6I6I6: 789  
Code figure for BUFR (Code table 0 01 007): 789  
Code figure for GRIB Edition 2: 789

**Comment by marijanacrepulja** [comment]
@amilan17 could you please create the branch for this issue
