### ISSUE TITLE
Add new entries to C-8 to identify SMAP instrument on SMAP spacecraft

### ISSUE THREAD

**Issue by SimonElliottEUM** [wmo-im/CCT#104]
# Summary and purpose

This document proposes new entries to Common Code Tables C-8 to identify the SMAP instrument on the SMAP satellite

# Action proposed

The meeting is kindly invited to review and approve the proposed new entries for inclusion within the next update to the WMO Manual on Codes.

# Discussions

The SMAP data created by NASA and passed from NOAA's PDA system to EUMETSAT, where they are formatted in BUFR by EUMETSAT and passed to ECMWF only. An identifier for the SMAP instrument is required

# Detailed proposal

Add the following entry to Common Code Table C-8

Code: 433  
Agency: NASA  
Type: MW radiometer  
Instrument short name: SMAP  
Instrument long name: Soil Moisture Active-Passive

**Comment by amilan17** [comment]
@SimonElliottEUM @marijanacrepulja 

From what I can tell, the satellite is called SMAP not the instrument. Does this matter?

**Comment by marijanacrepulja** [comment]
@amilan17 the same name is used for both. @SimonElliottEUM please correct me it that is not right.

**Comment by SimonElliottEUM** [comment]
I believe both the satellite and instrument are called SMAP. See WMO's OSCAR Space:
https://space.oscar.wmo.int/satellites/view/smap
https://space.oscar.wmo.int/instruments/view/smap
