### ISSUE TITLE
Change name of Turkey

### ISSUE THREAD

**Issue by amilan17** [wmo-im/CCT#108]
# Summary and purpose
copy of email circa 9 June 2022
_Please note that the Republic of Turkey has changed its official name to the Republic of Türkiye on 26 May 2022, through a request submitted to the UN Secretary-General by the country's Ministry of Foreign Affairs. The United Nations HQ and UNOG has adopted this change. 

WMO CPDB and Community Platform are being updated with "Türkiye".  Please update all your respective databases accordingly and bear this in mind in your official communications. Changes will also be made to the website with a transition period. 

Many thanks, 
Dr Paul D. EGERTON_

# Action proposed
Replace references of Turkey with Republic of Türkiye. 

# Discussions

# Detailed proposal

**Comment by amilan17** [comment]
@amilan17 will update branch

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022) notes: 

@marijanacrepulja will verify branch

**Comment by amilan17** [comment]
@marijanacrepulja branch is updated.

**Comment by marijanacrepulja** [comment]
@amilan17 It looks good, many thanks. Moved to "Ready for FT approval procedure"

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023](https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023) notes: 

ready for FT
