### ISSUE TITLE
Add 3 new entries to C-2 for radiosondes of China

### ISSUE THREAD

**Issue by Annie-FangZHAO** [wmo-im/CCT#11]
# Summary and purpose
This document proposes new entries to Common Code Tables C-2 to identify new radiosondes of China.

# Action proposed
The meeting is kindly invited to review the proposed new entries and approve it for pre-operational use and inclusion within the next update to the WMO Manual on Codes.

# Discussions
GTS1-1(31/131), GTS1(32/132) and GTS 1-2(33/133) radiosondes have been operational used in upper-air observation system of CMA for ten years. Since 2012, many technical transformations have been made and the improved new instruments has been named as GTS13, GTS12 and GTS11 correspondingly.

From January 15 2020, CMA has stopped the dual dissemination of TEMP and PILOT, all reports are disseminated in BUFR only. In order to encode radiosonde type (0 02 011) in BUFR message of TEMP and PILOT report for GTS13, GTS12 and GTS11, we’d like to request 3 new entries to Common Code Tables C-2 to identify each of them.

# Detailed proposal
Add new entries to Common Code Tables C-2:
|date of assignment of number|code figure for rara|code figure for BUFR(code table 0 02 011)|Radiosonde type|
|:---:|:---:|:---:|:---:|
|??/11/2020| Not available |200| Nanjing GTS11 (China )|
|??/11/2020| Not available |201| Shanghai GTS12 (China)|
|??/11/2020| Not available |202| Taiyuan GTS13 (China)|

The brief introduction of 3 radiosondes are as follows:
|Type|Manufacturer|
|:---:|:---:|
|GTS11|Nanjing Daqiao Machine Co., Ltd.|
|GTS12|Shanghai Changwang Weather Technology Co., Ltd.|
|GTS13|Taiyuan Radio factory|

- The temperature sensor is coated with a rod-shaped thermistor with white paint and changed to a bead-shaped thermistor vacuum-sprayed aluminum radiation-proof coating. 
- The humidity sensor has been changed from a humidity-sensitive resistor to the HC103M2 type capacitance by the E + E company.
- The pressure sensor is silicon piezoresistance.
- It operates at 1675MHz and compatible with GFE(L)  secondary wind-finding radar.
- The repeatability of each radiosonde sensor: temperature ≤ 0.2K; humidity ≤ 6%; air pressure ≤ 1hPa (altitude below 100hPa).

**Comment by efucile** [comment]
Dear @Annie-FangZHAO 
can you please write your proposal in the template in the first box? We don't accept word files for the proposal. Thanks

@jitsukoh we need to make sure that all the proposals are made using the template otherwise it becomes difficult for us to process them

**Comment by Annie-FangZHAO** [comment]
> Dear @Annie-FangZHAO
> can you please write your proposal in the template in the first box? We don't accept word files for the proposal. Thanks
> 
> @jitsukoh we need to make sure that all the proposals are made using the template otherwise it becomes difficult for us to process them

Dear @efucile 
Sorry for the delay in response. I didn't receive the notification email from GitHUB of your comment, untile yesterday Xiaoxia sent me a message. The proposal has been revised using the template. 
Bye the way, for the milestone, could we separate pre-operational use from FT-202-2? Thank you.

**Comment by Annie-FangZHAO** [comment]
@chenxiaoxia2019 @efucile @jitsukoh 
I reviewed new entries to C-2 in the FT2020-2 branch for CCT. Everything looks fine. Thank you.

**Comment by amilan17** [comment]
SUMMARY: Add entries to Common Code Table C-2.

**Comment by amilan17** [comment]
Approved by FT-2020-2.
