### ISSUE TITLE
Additions to Common Code Table C-3 Instrument make and type for water temperature profile measurements.

### ISSUE THREAD

**Issue by vturpin** [wmo-im/CCT#110]
# Summary and purpose

This document proposes new entries in Common Code Table C3 in order to represent the full range of profiling floats used.
Stakeholder: 
Victor Turpin: [vturpin@ocean-ops.org](mailto:vturpin@oceanops.org).
Thierry Carval: [tcarval@ifremer.fr](mailto:tcarval@ifremer.fr)
Znghong Liu: [liuzenghong@139.com](mailto:liuzenghong@139.com)

# Action proposed

The team is requested to approve the contents for inclusion in the next update to the WMO manual on Codes. The team is also requested to approve the new entries for pre-operational use.

# Discussions

New models and combinations of Argo floats and sensors are in use by the oceanographic community to measure the water temperature profile. OceanOPS, on behalf of the Argo community, has proposed the additions to Common Code Table C3 listed below to fully reflect the combinations in use.

# Detailed proposal

Add the following to Common Code Table C-3 Instrument make and type for water temperature profile measurement with fall rate equation coefficients.

CodeFigureForIXIIXIX | CodeFigureForBUFR | InstrumentMakeAndType_en | EquationCoefficients_a | EquationCoefficients_b | Status
-- | -- | -- | -- | -- | --
881 | 881 | HM4000 SBE |   |   |  
882 | 882 | HM6000 SBE |   |   |

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-4.10.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-4.10.2022.)  meeting notes: 

@amilan17 udpate branch

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022) notes: 

@marijanacrepulja will verify branch

**Comment by marijanacrepulja** [comment]
@amilan17 thanks for updating branch, all looks good. Moved issue "Ready for FT Approval Procedure"

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023](https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023) notes: 

ready for FT

**Comment by vturpin** [comment]
When does <html><body>


881 | 881 | HM4000 SBE 
882 | 882 | HM6000 SBE


</body>
</html>

be visible here: https://github.com/wmo-im/CCT/blob/master/C03.csv ?

**Comment by amilan17** [comment]
@vturpin Right now it's in the PR, I will merge it into master after the next task team meeting. The republication of the manual with these values could take up to a year. hope this helps.

**Comment by vturpin** [comment]
Yes super clear. thanks ;)
