### ISSUE TITLE
C08.csv, new entry to identify GEMS and OMPS-limb instruments

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#113]
### Initial request

This document proposes new entries to Common Code Tables C-8 to identify the GEMS instrument on the GEO-KOMPSAT-2B satellite, OMPS-limb

### Amendment details

Add new entries to Common Code Table C-8:  
|Code|Agency|Type|Instrument short name|Instrument long name|  
|:---:|:---:|:---:|:---:|:---:|  
|689| ME (NIER) |  Spectrometer | GEMS| Geostationary Environmental Monitoring Spectrometer|  
|960| NASA|Total and profile ozone| OMPS-limb | Ozone Mapping and Profiler Suite

Update name for OMPS to OMPS-nadir  to be consistent with WMO OSCAR
|Code|Agency|Type|Instrument short name|Instrument long name| 
|:---:|:---:|:---:|:---:|:---:| 
|947| NASA|Total and profile ozone| OMPS-nadir | Ozone Mapping and Profiler Suite

### Requestor(s)

Roberto Ribas, Antje Inness, Marijana Crepulja (all from ECMWF)

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-8

### Expected impact of change

MEDIUM

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-4.10.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-4.10.2022.)  meeting notes: 

@amilan17 update branch

**Comment by SimonElliottEUM** [comment]
For GEMS, I propose to change the agency to "ME (NIER)". NIER is the National Institute for Environmental Reseach in Korea, and they are the actual ones dealing with the instrument.

I have asked the CGMS group to comment and will confirm by end of October.

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM Many thanks for your help with this. I have updated the proposal with the proposed agency name.

**Comment by SimonElliottEUM** [comment]
@amilan17 @marijanacrepulja there was no more input from the CGMS Group. Noting that you already updated the proposal to with the proposed agency name, it is now in line with the CGMS Group. Thanks.

**Comment by marijanacrepulja** [comment]
@amilan17 branch is updated. Please confirm and move to validated. Thanks

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022) notes: 

@amilan17 verify branch

**Comment by amilan17** [comment]
@marijanacrepulja looks good.
