### ISSUE TITLE
C13.csv, New sub-category for aerosol

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#114]
### Initial request

This document proposes new entry to Common Code Tables C-13 in order to identify aerosols

### Amendment details

Add the new code **4 - Aerosol**   to
COMMON CODE TABLE C–13:	International data sub-categories of data categories defined by entries in BUFR Table A

| DATA CATEGORIES  |     |  INTERNATIONAL DATA SUB-CATEGORIES|      |  
| ------------- | -------------| -------------| -------------|     
| Code figure  | Name  |  Code figure | Name|
| 8  |Physical/chemical constituents|  4 | Aerosol |   |   |

### Requestor(s)

Marijana Crepulja (ECMWF)

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-13

### Collaborators

Roberto Ribas (ECMWF)

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference-21.11.2022 notes: 
@amilan17 create branch
@marijanacrepulja will update branch

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-12-and-13.12.2022) notes: 

@marijanacrepulja will update branch

**Comment by marijanacrepulja** [comment]
@amilan17 I have updated the branch. Could you please verify and move to "Ready for FT Approval procedure".
 Many thanks.

**Comment by amilan17** [comment]
@marijanacrepulja looks good

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023](https://github.com/wmo-im/CCT/wiki/Teleconference-10.01.2023) notes: 

ready for FT
