### ISSUE TITLE
CCT 02 code value errors?

### ISSUE THREAD

**Issue by amilan17** [wmo-im/CCT#126]
### Details

<html>
<body>

Before | 99 | 99 | iMet-2/iMet-3200 GPS radiosonde with derived pressure from GPS height (South Africa) | Operational
-- | -- | -- | -- | --
  |   | Not available | 100 | Reserved for BUFR only | Operational
  |   | 01 | 101 | Not vacant | Operational
  |   | Not available | 102-106 | Reserved for BUFR only | Operational
  |   | 07 | 107 | Not vacant | Operational
  |   | Not available | 108-109 | Reserved for BUFR only | Operational
  | 01/01/2008 | *10* | 110 | Sippican LMS5 w/Chip Thermistor, duct mounted capacitance relative humidity sensor and derived pressure from GPS height | Operational
  | 01/01/2008 | *11* | 111 | Sippican LMS6 w/Chip Thermistor, external boom mounted...
....

</body>
</html>

### Requestor

Anna Milan (WMO), @amilan17

**Comment by amilan17** [comment]
@marijanacrepulja Is this an error?

**Comment by marijanacrepulja** [comment]
@amilan17 

I believe it is a mistake. It should be shifted to correspond with the header columns.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.2&3May.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.2&3May.2023) notes:

team reviewed quickly and have no objections

**Comment by amilan17** [comment]
@marijanacrepulja -- can you take another look at this? Apparently, this has been like this for a long time and I wonder if it's actually an error.... 

For reference, this is the table from 2019: [https://github.com/wmo-im/CCT/blob/2588ae92ab8ed5f1e11d0acccdb2d614839f9d91/C02.csv](https://github.com/wmo-im/CCT/blob/2588ae92ab8ed5f1e11d0acccdb2d614839f9d91/C02.csv)

(filter by "Not available")

**Comment by marijanacrepulja** [comment]
@amilan17 Can we find the proposal and double check it.

**Comment by amilan17** [comment]
The details are in the first comment of this issue. I opened it.

**Comment by amilan17** [comment]
![](https://github.com/wmo-im/CCT/assets/5168866/40e63354-9822-4def-ad75-f68a8fa760e8)

**Comment by amilan17** [comment]
I think we should close this an leave as-is.
