### ISSUE TITLE
New entry for CCT C-3 - "Navis_EBR SBE"

### ISSUE THREAD

**Issue by vturpin** [wmo-im/CCT#128]
### Initial request

Can we add the following entry to the CCT -C3: 
<html>
<body>
<p dir="auto"></p>

CodeFigureForIXIIXIX | CodeFigureForBUFR | InstrumentMakeAndType_en | EquationCoefficients_a | EquationCoefficients_b | Status
-- | -- | -- | -- | -- | --
869 | 869 | NAVIS_EBR, SBE conductivity sensor |   |   | Operational

</body>
</html>

### Amendment details

NAVIS_EBR  is an operational ocean profiling instrument equipped with SBE temperature sensor.
Both float and sensor passed through the Argo requierments.

### Requestor(s)

Victor Turpin (OceanOPS, Argo Data Management Team) - (@vturpin)
Thierry Carval (Coriolis, Argo Data Management Team) - (@tcarval)
Violeta Paba (BODC, Argo Data Management Team)- (@vpada)

### Stakeholder(s)

Argo Steering Team
Argo Data Management Team
Argo Data Assembly Centers
OceanOPS

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-4

### Expected impact of change

LOW

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.2&3May.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.2&3May.2023) notes:

team reviewed quickly and have no objections

**Comment by vturpin** [comment]
NAVIS_EBR, SBE conductivity sensor

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023 notes:
don't need "float serial number..."

**Comment by amilan17** [comment]
@marijanacrepulja can you check this PR? #139

**Comment by marijanacrepulja** [comment]
@amilan17 I have checked the PR. All looks good!

**Comment by SBS-EREHM** [comment]
Hi @amilan17  Eric Rehm here from Sea-Bird Scientific.  I still don't see that the Initial Request in this issue 869 : NAVIS_EBR  has been added to C-3.

CodeFigureForIXIIXIX | CodeFigureForBUFR | InstrumentMakeAndType_en | EquationCoefficients_a | EquationCoefficients_b | Status
-- | -- | -- | -- | -- | --
869 | 869 | NAVIS_EBR, SBE conductivity sensor |   |   | Operational

On the NVS Vocab Server side, they are apparently blocked on this before they put it in table NVS Table R08
https://github.com/nvs-vocabs/R08/issues/5

**Comment by vturpin** [comment]
@amilan17 
could you tell us when the change will be effective and visible in the https://github.com/wmo-im/CCT/blob/master/C03.csv and https://github.com/wmo-im/CCT/blob/master/xml/C03.xml 
I understand that the PR has been approved and assume this is just a matter of the new table to be released. Am I right ?
Thanks.
V.
