### ISSUE TITLE
CCT  08, new code for SSH instrument

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#129]
### Initial request

ECMWF is proposing a new code for SSH instruments in support ERA6.

### Amendment details

Add new entries to Common Code Table C-8:  
|Code|Agency|Type|Instrument short name|Instrument long name|  
|:---:|:---:|:---:|:---:|:---:|  
|7| DoD |Infrared radiometer| SSH | Special Sensor H 

### Requestor(s)

Marijana Crepulja(ECMWF)

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-8

### Expected impact of change

MEDIUM

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.2&3May.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.2&3May.2023)

@SimonElliottEUM will look at

**Comment by SimonElliottEUM** [comment]
I have passed this to the CGMS Task Group for their consideration. They have until 29 May to comment. So I can confirm by 1 June.

**Comment by SimonElliottEUM** [comment]
@amilan17 @marijanacrepulja this has now been past the CGMS TG-SDC and there were no issues raised, so it is fine from that perspective.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023 notes:
@marijanacrepulja will update branch
