### ISSUE TITLE
4 New entries for CCT C-3: [PROVOR_V - Jumbo SBE / PROVOR_V - Jumbo - RBR / PROVOR_III - Jumbo SBE / PROVOR_III - Jumbo RBR]

### ISSUE THREAD

**Issue by vturpin** [wmo-im/CCT#133]
### Initial request

Can we add the 4 follwing entry to the Code Table C-3 instrument make and type for water temperature profile measurements.
"PROVOR_V - Jumbo SBE" 
"PROVOR_V - Jumbo RBR"
"PROVOR_III - Jumbo SBE"
"PROVOR_III - Jumbo RBR"  

This is a request from Argo vocab management team https://github.com/nvs-vocabs/R23/issues/3

### Amendment details

"PROVOR_V - Jumbo SBE" - PROVOR_V - Jumbo float equipped with SBE temperature sensor 
"PROVOR_V - Jumbo RBR" - PROVOR_V - Jumbo float equipped with RBR temperature sensor 
"PROVOR_III - Jumbo SBE" - PROVOR_III - Jumbo SBE float equipped with SBE temperature sensor 
"PROVOR_III - Jumbo RBR" - PROVOR_III - Jumbo float equipped with RBR temperature sensor

### Comments

The Argo program is extending its measurement capacity to BGC variables and deep ocean.
This is impacting the number of float make part of the Argo fleet.
The CCT C-3 table should follow this development.

### Requestor(s)

Victor Turpin (OceanOPS, Argo Data Management Team) - (@vturpin)
Thierry Carval (Coriolis, Argo Data Management Team) - (@tcarval)
Violeta Paba (BODC, Argo Data Management Team)- (@vpada)

### Stakeholder(s)

AVTT
Argo program

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-4

### Expected impact of change

LOW

**Comment by amilan17** [comment]
@vturpin I'd like to close this issue, because almost the same as #134. Can you update #134 with any missing details?

**Comment by vturpin** [comment]
Sure,
This is done.
Thanks.
