### ISSUE TITLE
8 new entries for CCT C-3 for water temperature sensors 

### ISSUE THREAD

**Issue by vturpin** [wmo-im/CCT#134]
### Initial request

Can we add the 8 follwing entry to the Code Table C-3 instrument make and type for water temperature profile measurements.
884 - "SOLO_BGC, SBE"
885 - " SOLO_BGC, RBR"
886 - "SOLO_BGC_MRV, SBE"
887 - "SOLO_BGC_MRV, RBR"

888 - "PROVOR_V - Jumbo, SBE"
889 - "PROVOR_V - Jumbo, RBR"
890 - "PROVOR_III - Jumbo, SBE"
891 - "PROVOR_III - Jumbo, RBR"

This is a request from Argo Vocab Task Team : https://github.com/nvs-vocabs/ArgoVocabs/issues/109

### Amendment details

"PROVOR_V - Jumbo SBE" - PROVOR_V - Jumbo float equipped with SBE temperature sensor
"PROVOR_V - Jumbo RBR" - PROVOR_V - Jumbo float equipped with RBR temperature sensor
"PROVOR_III - Jumbo SBE" - PROVOR_III - Jumbo SBE float equipped with SBE temperature sensor
"PROVOR_III - Jumbo RBR" - PROVOR_III - Jumbo float equipped with RBR temperature sensor

"SOLO_BGC SBE" - SOLO_BGC float equipped with SBE temperature sensor
" SOLO_BGC RBR" - SOLO_BGC float equipped with RBR temperature sensor
"SOLO_BGC_MRV SBE" - SOLO_BGC_MRV float equipped with SBE temperature sensor
"SOLO_BGC_MRV RBR" - SOLO_BGC_MRV float equipped with RBR temperature sensor

### Comments

These request are the consequence of the capacity improvement of the Argo program tp measure BGC variables and deep ocean.
This is impacting the number of float make part of the Argo fleet.
The CCT C-3 table should follow this development

### Requestor(s)

Enter list of requestors.Victor Turpin (OceanOPS, Argo Data Management Team) - (@vturpin)
Thierry Carval (Coriolis, Argo Data Management Team) - (@tcarval)
Violeta Paba (BODC, Argo Data Management Team)- (@vpada)

### Stakeholder(s)

Argo Vocabulary Task Team
Argo program

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-4

### Expected impact of change

LOW

**Comment by vturpin** [comment]
To be added to the 4 entries above, can we add the 4 following entries to the Code Table C-3 instrument make and type for water temperature profile measurements.
"PROVOR_V - Jumbo SBE"
"PROVOR_V - Jumbo RBR"
"PROVOR_III - Jumbo SBE"
"PROVOR_III - Jumbo RBR"
This is a request from Argo vocab management team https://github.com/nvs-vocabs/R23/issues/3

Amendment details
"PROVOR_V - Jumbo SBE" - PROVOR_V - Jumbo float equipped with SBE temperature sensor
"PROVOR_V - Jumbo RBR" - PROVOR_V - Jumbo float equipped with RBR temperature sensor
"PROVOR_III - Jumbo SBE" - PROVOR_III - Jumbo SBE float equipped with SBE temperature sensor
"PROVOR_III - Jumbo RBR" - PROVOR_III - Jumbo float equipped with RBR temperature sensor

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023 notes:
assign numbers 884+;

**Comment by amilan17** [comment]
@marijanacrepulja Can you double check the branch to make sure that I updated it correctly?

**Comment by marijanacrepulja** [comment]
@amilan17 Many thanks for updating the branch. All looks good!
