### ISSUE TITLE
CCT-05, declaration of Sentinel-1C and Sentinel-1D satellites

### ISSUE THREAD

**Issue by ghajduch** [wmo-im/CCT#137]
### Initial request

ESA is currently operating two units of Sentinel-1 instrument (Sentinel-1A and Sentinel-1B). The launch
of a new unit called Sentinel-1C is planned in end of 2023, while the Sentinel-1D unit is under construction for
a launch at a date to be defined. The current BUFR format specification allows to annotate the
identification of the Sentinel-1A and Sentinel-1B unit. However, the BUFR table does not allow to annotate
the future Sentinel-1C and Sentinel-1D.

The request is about declaring Sentinel-1C and Sentinel-1D satellites.

Those fields are used in bufr products generated by ESA corresponding to swell information derived from Sentinel-1 Level 2 products, and considered for the assimilation in swell models.

### Amendment details

The master table 0 contains a code flag table describing the allowed values for spacecraft identifiers (code
table for class 1 identification 001007 (Satellite identifier).
Code 62 is used for Sentinel-1A and Code 63 is used for Sentinel-1B.

We request to add two new codes for Sentinel-1C and Sentinel-1D.

Reference to the table
For WMO 27
https://confluence.ecmwf.int/display/ECC/WMO%3D27+code-flag+table#WMO=27codeflagtable-CF_001007
For WMO 38
https://confluence.ecmwf.int/display/ECC/WMO%3D38+code-flag+table#WMO=38codeflagtable-CF_001007

### Comments

Ideally, we would prefer to use two consecutive code values for Sentinel-1C and Sentinel-1D.

### Requestor(s)

Guillaume Hajduch (Collecte Localisation Satellites), as Service Manager of the SAR Mission Performance Cluster (SAR-MPC) Service, on behalf of European Space Agency (ESA)
Muriel Pinheiro as Technical Officer of the SAR-MPC, and responsible of the QC and Calibration/Validation of Sentinel-1 mission.
Antonio Valentino  as support to Muriel Pinheiro

### Stakeholder(s)

The weather forecast community in charge of assimilation of swell observation in swell .
This is inter alia

Meteo France, Lotfi Aouf,
ECMWF Stephen English
ECMWF Carlo Buontempo 
ECMWF Jean Bidlot 
ECMWF Sean Healy 
ECMWF Saleh Abdalla 

### Publication(s)

Manual on Codes (WMO-No. 27), Volume ??, BUFR code table 0 01 007

### Expected impact of change

MEDIUM

### Collaborators

Manuel Goacolou, Collecte Localisation Satellite, 
Lotfi Aouf, Meteo France,

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.6.7.June.2023 notes:
@SimonElliottEUM will check with CGMS

**Comment by SimonElliottEUM** [comment]
@amilan17 @marijanacrepulja @ghajduch I have passed this to the CGMS Task Group for their consideration. They have until 20 June to comment. So I can confirm by 21 June.

**Comment by ghajduch** [comment]
Thanks a lot !

**Comment by SimonElliottEUM** [comment]
@amilan17 @marijanacrepulja @ghajduch The CGMS Task Group has not raised any objections, so we can go ahead from that perspective

**Comment by amilan17** [comment]
> How do I check the PR?

This is the link to the PR (it's also above the previous comment) #148, then click on the "files changed" tab. There you will see a diff. Let me know if you need more information.
