### ISSUE TITLE
CCT 05, new codes for FY-3F and FY-3G

### ISSUE THREAD

**Issue by shirley-xuelei** [wmo-im/CCT#143]
### Initial request

CMA has already launched the Fengyun Precipitation satellite, FY-3G, on April 16 this year, and will soon launch a new morning orbit satellite, Fengyun 3F satellite(FY-3F), in August. The request is about declaring FY-3G and FY-3F satellites.

### Amendment details

|Code figure for I6I6I6|Code figure for BUFR (Code table 0 01 007)|Code figure for GRIB Edition 2||
|----------------------|------------------------------------------|------------------------------|------|
|525                   |525                                       |525                           |FY-3F |
|526                   |526                                       |526                           |FY-3G |

### Requestor(s)

NMIC, CMA:
XUE Lei
NSMC, CMA:
QI Chengli

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-5

### Expected impact of change

None

**Comment by SimonElliottEUM** [comment]
@shirley-xuelei @amilan17 @marijanacrepulja I have passed this proposal to the CGMS Task Group on Satellite Data and Codes for their expert analysis. There were no objections or changes proposed, so we can consider these proposed CCT C-5 entries confirmed from the CGMS side. ✔

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM Many thanks for your support. 
I believe we can include this proposal in FT2023-2

**Comment by SimonElliottEUM** [comment]
> @SimonElliottEUM Many thanks for your support. I believe we can include this proposal in FT2023-2

Yes, I believe so to.

**Comment by shirley-xuelei** [comment]
@marijanacrepulja @SimonElliottEUM @amilan17 I submitted the new proposal for the new codes of FY-3F and FY-3G in C-5.  Could you please review it? Thank you.

> @shirley-xuelei @amilan17 @marijanacrepulja I have passed this proposal to the CGMS Task Group on Satellite Data and Codes for their expert analysis. There were no objections or changes proposed, so we can consider these proposed CCT C-5 entries confirmed from the CGMS side. ✔

@SimonElliottEUM Thank you for your support.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.13.July.2023](https://github.com/wmo-im/CCT/wiki/Teleconference.13.July.2023) notes:

@shirley-xuelei will update branch soon

**Comment by shirley-xuelei** [comment]
@amilan17 @marijanacrepulja I updated the branch just now.
