### ISSUE TITLE
 CCT-11, update with new entries for centre definition 

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#144]
### Initial request

This proposal is linked to BUFR proposal  (https://github.com/wmo-im/BUFR4/issues/160)  for updating entries for the BUFR descriptor 001035

### Amendment details

**Update Common Code Table C-11**

<!DOCTYPE html>

Code Figure | Originating centre
-- | --
293 | University of Bremen
294 | Netherlands Institute for Space Research (SRON)
295 | The Royal Belgian Institute for Space Aeronomy (BIRA-IASB)
296 | The French National Centre for Scientific Research (CNRS)
297 | The Nanjing Institute of Environmental Sciences (NIES)
298 | Dynamic Meteorology Laboratory (LMD)
299 | The Rutherford Appleton Laboratory (RAL)

### Requestor(s)

Enter list of requestors.

### Stakeholder(s)

Marijana Crepulja, Roberto Ribas (both from ECMWF)

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-4

### Expected impact of change

None

**Comment by marijanacrepulja** [comment]
@amilan17 could you please create branch for this issue. Many thanks

**Comment by amilan17** [comment]
@marijanacrepulja branch is ready for you
