### ISSUE TITLE
CCT-1 and CCT-11, new entry for AWI

### ISSUE THREAD

**Issue by SibylleK** [wmo-im/CCT#158]
### Initial request

A request for a new entry in Common Code Table 1 and 11 has been received from the AWI based in Bremerhaven, Germany. 

The climate model development team at Alfred Wegener Institute (AWI) would like to disseminate model runs from Finite-Element/volume Sea ice-Ocean Model (FESOM) as GRIB files for wider distribution. The model runs will include various CMIP type experiments, as well as digital twin simulations for the Destination Earth initiative. Further development is planned to ensure ease of data access and usability.

No changes are expected to GRIB templates. However, AWI would like to have their own originating center number to be reported in Section 1 of GRIB messages.

### Amendment details

The following new entry is requested in CCT-1 and CCT-11

| Code Figure | Meaning |
|  :-----: |  :-----: |
| 253 | Alfred Wegener Institute (AWI) |

### Requestor(s)

Sibylle Krebber (DWD)
Bimochan Niraula (Alfred Wegener Institute (AWI))

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-1
Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-11

### Expected impact of change

None

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/20.to.22.September.2023](https://github.com/wmo-im/CCT/wiki/20.to.22.September.2023) notes: 

team accepts proposal

**Comment by SibylleK** [comment]
Branch is updated.
