### ISSUE TITLE
CCT 08, new entry to identify TEMPO instrument

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#160]
### Initial request

In support to data assimilation for NWP there is a requirement to define TEMPO instrument.  Short Name and Long Name is define at https://space.oscar.wmo.int/instruments/view/tempo

### Amendment details

The team is kindly asked to validate the proposed new entries to be included within the next update to the WMO Manual on Codes.

Add new entries to Common Code Table C-8:  
|Code|Agency|Type|Instrument short name|Instrument long name|  
|:---:|:---:|:---:|:---:|:---:|  
| 435 | NASA | Spectrometer| TEMPO | Tropospheric Emissions: Monitoring of Pollution

### Requestor(s)

Marijana Crepulja, Roberto Ribas (both from ECMWF)

### Stakeholder(s)

CAMS

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-8

### Expected impact of change

MEDIUM

**Comment by SimonElliottEUM** [comment]
@marijanacrepulja @amilan17 I have passed this to the CGMS Group and asked for their feedback by 19 October.

**Comment by SimonElliottEUM** [comment]
@marijanacrepulja @amilan17 The CGMS Task Group on Satellite Data and Codes has not raised any objections, so we can go ahead with this proposal

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.21.22.November.2023 notes:
branch is ready for validation

**Comment by marijanacrepulja** [comment]
@amilan17 branch updated
