### ISSUE TITLE
CCT 05 request to EUMETSAT, ESA, EC to identify CO2M-A satellite

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#161]
### Initial request

We are kindly asking organisations in charge of the satellite to propose final name and identification of CO2M-A. We would like to have entry in CCT 5 soon to support data assimilation of CO2M-A observation. We understand the launch is planned for 2025 according to WMO OSCAR, but sample data are already available. 

https://space.oscar.wmo.int/satellites/view/co2m_a#:~:text=Mission%3A%20to%20measure%20how%20much,covering%20a%20period%20%3E%207%20years.

### Amendment details

In Common Code table C-5: Satellite identifie

Code | Name
----- | --------
6 | CO2M-A
7 | CO2M-B
8 | CO2M-C

### Requestor(s)

Copernicus Atmosphere Monitoring Service (CAMS)

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-5

### Expected impact of change

MEDIUM

**Comment by SimonElliottEUM** [comment]
@marijanacrepulja @amilan17 I have contact the programme management for CO2M to ask them to arrange for the formalisation of the satellite names. When we get this we will be able to ask for numbers in CCT-5 (and a WIGOS Station Identifier at the same time).

**Comment by SimonElliottEUM** [comment]
According to Article 18 of the IA between EUMETSAT and ESA, ESA will register the name, etc with UN in accordance with the Convention of Objects Launched into Outer Space (15/09/1976). Just as ESA went through WMO and TT-TDCF for Sentinel-1C and -1D number (CCT Issue 137), I am sure they will do the same again for the CO2M/Sentinel-7 satellites. We are finding out from ESA when they plan to do this and should have an answer by early November.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.21.22.November.2023 notes:
still waiting for feedback from ESA

**Comment by SimonElliottEUM** [comment]
I have asked my colleagues who are in direct contact with ESA on this for an update.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.16.May.2024: 
still waiting on ESA

**Comment by SimonElliottEUM** [comment]
@marijanacrepulja @amilan17 
Fresh news today. The names for CCT C-5 are:
CO2M-A
CO2M-B
CO2M-C
No gaps, all upper case, simple hyphen after the "M". Please go ahead on this basis. I propose entries 6, 7, and 8 in CCT C-5 respectively.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes:
@antoinemerle will update the branch

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2.July.2024 notes
branch is updated

**Comment by antoinemerle** [comment]
Commit and push ( 4d5120b6c6372f35ec98953c2a436dfd97c2093f / c8907a19af21c7737b8e815f8e2a5e1002b24019)

![image](https://github.com/wmo-im/CCT/assets/10506061/a555abb3-cafd-44a5-9424-3ba86c69662d)
