### ISSUE TITLE
Move CCT-06 into the GitHub repository (Units)

### ISSUE THREAD

**Issue by amilan17** [wmo-im/CCT#162]
### Details

It would be useful to have the units in the repository. Noting that CSV is probably not the right solution, but ascidoc with LaTeX might be useful solution. 

### Requestor

Anna Milan (WMO), @amilan17 and the @wmo-im/tt-tdcf

**Comment by amilan17** [comment]
![](https://github.com/wmo-im/CCT/assets/5168866/08d86e25-a7e0-4558-a151-a4e29de0a618)

**Comment by amilan17** [comment]
Initial creation of CSV for discussion: 

[https://github.com/wmo-im/CCT/blob/162-move-cct-06-into-the-github-repository-units/C06.csv](https://github.com/wmo-im/CCT/blob/162-move-cct-06-into-the-github-repository-units/C06.csv)

**Comment by tomkralidis** [comment]
Great work!  Comments:
- update `CodeFigiure` to `CodeFigure`
- I see some values are quoted?  Is this to preserve leading zeros/etc., or something else?

**Comment by amilan17** [comment]
This CSV was added to FT2024-2 branch.
