### ISSUE TITLE
CCT 05 request to identify GOSAT-2

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#163]
### Initial request

We are kindly asking for identification of GOSAT-2. 
Information from OSCAR
https://space.oscar.wmo.int/satellites/view/gosat_2

### Amendment details
141,GOSAT-2

### Requestor(s)

Enter list of requestors.

### Stakeholder(s)

ECMWF
Copernicus Atmosphere Monitoring Service (CAMS)
### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-5

### Expected impact of change

MEDIUM

**Comment by SimonElliottEUM** [comment]
I have written to JAXA confirming we can go ahead - I have proposed entry 141 for now; GOSAT has entry 140

**Comment by marijanacrepulja** [comment]
Thank you @SimonElliottEUM

**Comment by SimonElliottEUM** [comment]
I have passed this to the CGMS Group and asked for their feedback by 20 November.

**Comment by SimonElliottEUM** [comment]
The CGMS Group did not raise any objections, so we are clear to proceed.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.21.22.November.2023 notes:
@SimonElliottEUM update branch

**Comment by SimonElliottEUM** [comment]
Hallo @amilan17 , we have updated the branch
https://github.com/wmo-im/CCT/commit/b100965c3c23afb1be7c9461376b2f55d0283094
