### ISSUE TITLE
CCT 02, new entries to identify RadiosondeSoundingSystems of China

### ISSUE THREAD

**Issue by shirley-xuelei** [wmo-im/CCT#166]
### Initial request

Satellite navigation radiosonde adopts baseband RF SoC integrated design navigation and positioning technology, realizes high accuracy and high spatial resolution measurement of atmospheric temperature, humidity, barometric pressure and wind direction and speed from 0 to 36km altitude, provides satellite navigation information and status information, and adopts GFSK wireless FM communication to send the collected data to the ground receiving and processing system in real time through P-band frequency band. The humidity adopts heated polymer moisture-sensitive capacitor, which can meet the demand of high altitude climate observation and has higher measurement accuracy.

### Amendment details

|CodeFigureForrara|CodeFigureForBUFR|RadiosondeSoundingSystemUsed            |
|-----------------|-----------------|----------------------------------------|
|Not available    |204              |Beijing GTH1 (China)                    |
|Not available    |205              |Nanjing GTH2 (China)                    |
|Not available    |206              |Tianjin GTH3 (China)                    |
|Not available    |207              |Aerospace Newsky Technology GTH4 (China)|
|Not available    |208              |Taiyuan GTH5 (China)                    |
|Not available    |209              |Shanghai GTH6 (China)                   |

### Requestor(s)

LI Xin, CMA Meteorological Observation Center
XUE Lei, National Meteorological Information Center, CMA

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-2

### Expected impact of change

None

**Comment by shirley-xuelei** [comment]
@amilan17 I have updated the branch of #166.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.21.22.November.2023 notes:
branch is updated and ready for validation
