### ISSUE TITLE
Add new CCT 13 entry for radio occultation data from non-satellites

### ISSUE THREAD

**Issue by jbathegit** [wmo-im/CCT#168]
### Initial request

In CCT 13, there is already an entry 50 for radio occultation sounding under Data Category 3 (=Vertical soundings (satellite)).  However, radio occultation data profiles can also be observed from non-satellite platforms, including from aircraft or from high-altitude balloons.  To that end, we propose a similar entry under Data Category 2 (=Vertical soundings (other than satellite)).

### Amendment details

New entry in CCT 13:

| Data Category | Data Category name | International Subcategory | International Subcategory name |
|-----|-----|-----|-----|
| 2 | Vertical soundings (other than satellite) | 50 | Radio occultation sounding |

### Requestor(s)

Jeff Ator (U.S. NOAA/NWS)
Jennifer Haase, Ph D (U.S. Scripps Institute of Oceanography)

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-13

### Expected impact of change

None

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.21.22.November.2023 notes:
Jeff introduced the proposal; team agrees to proposal; @jbathegit update the branch;

**Comment by jbathegit** [comment]
@amilan17

The branch has been updated - thanks!
