### ISSUE TITLE
CCT-8 : EUMETSAT : EPS Sterna Radiometer (MWR) - AWS 1 new entry

### ISSUE THREAD

**Issue by antoinemerle** [wmo-im/CCT#172]
### Initial request

This issue is requested by **EUMETSAT** to create a new entry in the **common code C-8** table for :  
- Agency : `ESA`
- Type : `Radiometer`
- Short name : `MWR`
- Long name is : `EPS Sterna Radiometer`
- code : `209`

### Amendment details

the expected file on GitHub to be updated is : 
- https://github.com/wmo-im/CCT/blob/master/C08.csv

```csv
209,ESA,Radiometer, MWR,EPS Sterna Radiometer, Operational
```

![image](https://github.com/wmo-im/CCT/assets/10506061/0616c0ea-24a9-4e6b-bf5b-c92f9a4a6472)

### Comments

- [ ] @antoinemerle will push the changes on the given branch provided by WMO

### Requestor(s)

@SimonElliottEUM @antoinemerle 

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-4

### Expected impact of change

None

**Comment by antoinemerle** [comment]
Hi @amilan17 ,

Commit : https://github.com/wmo-im/CCT/commit/8cb5184a0edcfa6436e9afb03c4e551010a57881

Branch has been updated

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference.10.January.2024](https://github.com/wmo-im/CCT/wiki/Teleconference.10.January.2024) notes:

@amilan17 to very branch;
