### ISSUE TITLE
CCT-8 : EUMETSAT : Microwave Radiometer (MW radiometer) - SWOT new entry

### ISSUE THREAD

**Issue by antoinemerle** [wmo-im/CCT#173]
### Initial request

This issue is requested by EUMETSAT to create a new entry in the common code C-8 table for :  
- Agency : `NASA`
- Type : `Radiometer`
- Short name : `MW radiometer`
- Long name : `Microwave radiometer`
- Code : `368`

### Amendment details

the expected file on GitHub to be updated is : 
- https://github.com/wmo-im/CCT/blob/master/C08.csv

```csv
368,NASA,Radiometer, MW radiometer,Microwave radiometer, Operational
```

![image](https://github.com/wmo-im/CCT/assets/10506061/222ffbb6-bbf3-45b6-b339-7ea6288acd6a)

### Comments

- [x] @antoinemerle will push the changes on the given branch provided by WMO

### Requestor(s)

@SimonElliottEUM 
@antoinemerle 

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-4

### Expected impact of change

None

**Comment by amilan17** [comment]
@amilan17 to validate branch
