### ISSUE TITLE
acceptance of open source license terms for IBL software contributions

### ISSUE THREAD

**Issue by efucile** [wmo-im/CCT#19]
Hi @marianmajan-ibl and @tomkralidis,

can you please confirm that all your contributions to the following repositories
https://github.com/wmo-im/GRIB2
https://github.com/wmo-im/BUFR4
https://github.com/wmo-im/CCT

are given under the following license:

https://github.com/wmo-im/GRIB2/blob/master/LICENSE.md
https://github.com/wmo-im/BUFR4/blob/master/LICENSE.md
https://github.com/wmo-im/CCT/blob/master/LICENSE.md

included in the repositories?

Thanks

**Comment by erget** [comment]
@efucile I think that if you send a PR to a repo with a given license, and in your PR you don't remove that license, you're essentially licensing your work under that license and therefore it's accepted implicitly.

**Comment by efucile** [comment]
@erget thanks. I realized that there wasn't a license in the repo when we made the PR and I want to be sure that the new license is accepted.

**Comment by tomkralidis** [comment]
@efucile I confirm.

**Comment by marianmajan-ibl** [comment]
@efucile I confirm we accept the license.

**Comment by efucile** [comment]
thanks @marianmajan-ibl and @tomkralidis
