### ISSUE TITLE
new CCT C-1/11, C-5 and C-8 entries for commercial providers of radio occultation data

### ISSUE THREAD

**Issue by jbathegit** [wmo-im/CCT#195]
### Initial request

This document proposes new entries in Common Code Tables C-1, C-11, C-5 and C-8 for commercial providers of radio occultation data.  The commercial field continues to expand, including for providers who may not launch satellites themselves but who instead subcontract with other commercial providers to carry their instruments as part of their payload.

Any data purchased by NOAA will be negotiated with a stipulation to allow the data to be shared freely with others and without restriction in real-time.

### Amendment details

Add the following new CCT entries:

COMMON CODE TABLE C–1: Identification of originating/generating centre
COMMON CODE TABLE C-11: Originating/generating centres
Code | Meaning
----- | --------
182 | tomorrow.io

COMMON CODE TABLE C–5: Satellite identifier
Code | Meaning
----- | --------
768   |  Loft Orbital YAM Longbow
769   |  tomorrow.io 6U CubeSat

COMMON CODE TABLE C–8: Satellite instruments
Code |    Agency |    Type    |    Instrument short name  | Instrument long name 
 ----  |    -------  |    -----   |    ------------------------  | -----------------------       
536  |  tomorrow.io |  Radiometer |  MWS  |  Microwave sounder
537  |  tomorrow.io |  Radar | KAPR |  Ka band precipitation radar

### Requestor(s)

- Jeff Ator (NOAA)
- Dr. Simon Elliott (EUMETSAT)
- Heikki Pohjola (WMO)
- Dr. Benjamin Ruston (UCAR)
- Jonathan Brandmeyer (PlanetiQ)

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Tables C-1/11, C-5, C-8

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.16.May.2024 notes: 
Jeff introduced the proposal; @SimonElliottEUM will pass the satellite ids through the CGMS group;

**Comment by SimonElliottEUM** [comment]
I have asked the CGMS group for their feedback by Friday 14 June.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2024.June.4and5 notes:
waiting for CGMS confirmation after 14 June

**Comment by SimonElliottEUM** [comment]
@amilan17 @jbathegit There were no objections raised by the CGMS Task Group on Satellite Data and Codes, so we can move ahead with this proposal now

**Comment by jbathegit** [comment]
@SimonElliottEUM thanks for letting us know

@amilan17 the development branch is now updated with the above entries

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes:
branch is updated and ready for validation
