### ISSUE TITLE
new CCT C-13 entry for long-duration balloon observations

### ISSUE THREAD

**Issue by jbathegit** [wmo-im/CCT#196]
NOAA/NWS has begun purchasing long-duration balloon data from the private company [WindBorne](https://windbornesystems.com/).  The data is BUFR format and is similar in nature to radiosonde and dropsonde data, in that it contains measurements of pressure, GPS height, temperature, moisture, and winds at a number of vertical levels, and with a unique time and lat/long reported as well for each vertical level. 

However, and unlike for radiosondes and dropsondes, a single balloon may stay aloft for days or even weeks at a time, constantly ascending and descending as guided remotely from a ground site.  Furthermore, a single ascent or descent can last much longer than for a typical radiosonde or dropsonde, so instead of issuing a full report once an ascent or descent is complete (i.e. each BUFR message containing one BUFR data subset with delayed replication of multiple levels), numerous levels of this data will instead be continuously and successively accumulated and disseminated as separate BUFR data subsets after a certain threshold of time or vertical distance has elapsed.  So for this long-duration balloon data, each BUFR message will contain multiple compressed data subsets, each containing all of the data at a single vertical level during a certain time or vertical distance interval.  And in that sense each report will end up being more akin to a single-level data report in BUFR Data Category 4, with receiving centers needing to locally re-assemble reports from multiple BUFR messages if they later wish to view all of the data from a full ascent or descent period of any balloon.

The data is planned to be disseminated with allowed sharing by all global NWP centers.  However, the data is not fully free and open and therefore may not be shared with any private or commercial entities outside of global NWP centers.  In preparation for this new type of data, we would like to request a new entry in Common Code Table C-13, as noted below.

### Amendment details

COMMON CODE TABLE C-13: Data subcategories of BUFR Table A data categories
Category Code | Category Meaning | Subcategory Code | Subcategory Meaning
:-----: | -------- | :-------: | -------- |
4 | Single level upper-air data (other than satellite) | 3 | Long-duration balloon

### Requestor(s)

Jeff Ator (NOAA)

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-13

### Expected impact of change

None

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.16.May.2024 notes:
Jeff introduced the proposal;

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2024.June.4and5 notes:
waiting for CGMS confirmation after 14 June

**Comment by amilan17** [comment]
oops! too many notes too fast. :)

**Comment by jbathegit** [comment]
The development branch has now been updated

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes:
branch is updated and ready for validation
