### ISSUE TITLE
Update GitHub actions

### ISSUE THREAD

**Issue by amilan17** [wmo-im/CCT#197]
### Details

From what I understand, the check can fail for two reasons. 
1) The XML is already generated in branch and there are no changes. 
2) Branch protections on master prevents automated updates.

I think the actions should follow the logic of A or B as described below. 

Workflow A: 
* XML is generated in branch and action/check passes
* Branch is merged into master
* Check passes or there is no action/check at this point

Workflow B: 
* XML is not generated in the branch
* Branch is merged into master
* XML is generated

### Requestor

Anna Milan (WMO), @amilan17

**Comment by amilan17** [comment]
@antoinemerle will fix the action

**Comment by antoinemerle** [comment]
HI @amilan17 , fixed in a11d1334a9d87459fb238dc5c6c51b87bd443e57
🎊
