### ISSUE TITLE
New entries to C13 sub category to identify tropical cyclone forecast from machine learning 

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#198]
### Initial request

In preparations to disseminate forecasted tropical cyclone tracks  from machine learning models, there is a need to introduce new data subcategories to identify these products. 

### Amendment details

Add the new codes   to
COMMON CODE TABLE C–13:	International data sub-categories of data categories defined by entries in BUFR Table A

| DATA CATEGORIES  |     |  INTERNATIONAL DATA SUB-CATEGORIES|      |  
| ------------- | -------------| -------------| -------------|     
| Code figure  | Name  |  Code figure | Name|
| 7 | Synoptic features|  3 |Forecast tropical cyclone from machine learning deterministic system|   |   |
| 7 | Synoptic features|  4 |Forecast tropical cyclone from machine learning  ensemble prediction system   |   |

### Requestor(s)

Marijana Crepulja (ECMWF)

### Stakeholder(s)

ECMWF member states
WMO

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-4

### Expected impact of change

None

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.16.May.2024 notes:

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2024.June.4and5 notes:
branch is ready to edit

**Comment by marijanacrepulja** [comment]
@amilan17 the branch is updated

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes:
branch is updated and ready for validation
