### ISSUE TITLE
Update C08.csv for CrIS

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#199]
### Initial request

It is noted that entry for CrIS in CCT 08 needs to be updated with the correct name.

### Amendment details

620,NOAA,Atmospheric temperature and humidity sounder,CrIRS/NP,Cross-track infrared sounder/NPOESS,Operational

should be 
620,NOAA,Atmospheric temperature and humidity sounder,CrIS/NP,Cross-track infrared sounder/NPOESS,Operational

### Requestor(s)

Marijana Crepulja (ECMWF)

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-4

### Expected impact of change

None

**Comment by SimonElliottEUM** [comment]
I agree that this simple typographic error should be corrected. No need to bother CGMS with this.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.16.May.2024 notes:
just a typo.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes:
@marijanacrepulja  will update branch; and then is is ready for validation

**Comment by marijanacrepulja** [comment]
@amilan17 I have updated the branch
