### ISSUE TITLE
Validate machine-readable legacy format

### ISSUE THREAD

**Issue by efucile** [wmo-im/CCT#20]
Machine-readable legacy format has been included in the master branch. We need to verify that the format satisfies users requirements.

**Comment by efucile** [comment]
xml format here (https://github.com/wmo-im/CCT/tree/master/xml)

**Comment by amilan17** [comment]
In progress. See https://github.com/wmo-im/BUFR4/issues/23

**Comment by amilan17** [comment]
[CCT-2020-Nov-10.zip](https://github.com/wmo-im/CCT/files/5516728/CCT-2020-Nov-10.zip)
Please test this new zip of CCT XML. 

Differences (aside from amendments) from May 2020 version:
1. No TXT files
2. No XSD files
3. Schema declaration is removed `xsi:noNamespaceSchemaLocation="Common_C02_20200506_en.xsd"`
4. 'Common', date and '_en' removed from XML tags. For example, `Common_C02_20200506_en` is now just `C02`
5. there are some empty xml tags, for example `<DateOfAssignment_en/>`.

**Comment by erget** [comment]
These imported just fine into the Vocabulary Manager.

**Comment by amilan17** [comment]
@wmo-im/tt-tdcf -- Can anyone else on the team confirm that this works for you? 
https://github.com/wmo-im/CCT/files/5516728/CCT-2020-Nov-10.zip
Thanks

**Comment by marijanacrepulja** [comment]
Hi @amilan17, 

I have used csv files from branch createMachineCodes, and it worked OK for me. Could you please just confirm that is the right branch to pull latest csv files. Many thanks.

**Comment by amilan17** [comment]
@marijanacrepulja - Thank you. After the validation is complete, I will merge the createMachineCodes branch with Master.

**Comment by amilan17** [comment]
Machine-readable codes are published to https://community.wmo.int/activity-areas/wmo-codes/manual-codes/latest-version.
