### ISSUE TITLE
CCT 08, new codes for WindRAD on FY-3E and FY-3J

### ISSUE THREAD

**Issue by shirley-xuelei** [wmo-im/CCT#200]
### Initial request

This document proposes new entries to Common Code Tables C-8 to identify WindRAD instruments on FY-3E and FY-3J.
https://space.oscar.wmo.int/instruments/view/windrad

### Amendment details

|Code|Agency|Type                                          |Instrument short name|Instrument long name|
|----|------|----------------------------------------------|---------------------|--------------------|
|988 |CMA   |Conical scanning dual-frequency scatterometer |WindRAD              |Wind Radar          |

### Requestor(s)

SHANG Jian, NSMC, CMA
XUE Lei，NMIC, CMA

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-8

### Expected impact of change

None

**Comment by SimonElliottEUM** [comment]
As this entry comes from CMA and is for CMA's instrument, there is no need to bother the CGMS Task Group with, and I believe we can simply push ahead.

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2024.June.4and5 notes: 
Lei introduced the proposal;

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes:
@shirley-xuelei will update the branch
