### ISSUE TITLE
CCT C-6, List of units for TDCFs: addition of missing compound units

### ISSUE THREAD

**Issue by david-i-berry** [wmo-im/CCT#202]
### Initial request

A number of compound units listed in BUFR Table B are missing from CCT C-6. This amendment adds those units.

### Amendment details

**Add the following entries to CCT C-6**

Code figure | Meaning | Conventional abbreviation | Abbreviation in IA5 | Abbreviation in ITA2 | definition in base units
-|-|-|-|-|-
845|per Kelvin|K^-1|K-1||
846|square Kelvin|K^2|K2||
847|logarithm square metre per square metre|log(m^2 m^-2)|log(m2 m-2)||
848|logarithm cubic metre per square metre|log(m^3 m^-2)|log(m3 m-2)||
849|kilograms per square metre per hour|kg m^-2 h^-1|kg m-2 h-1||
850|Kelvin per Kelvin|K K^-1|K K-1||
851|Watts per square metre per steradian per micro-metre|W m^-2 sr^-1 um^-1|W m-2 sr-1 um-1||
852|Candela per square metre|Cd m^-2|Cd m-2||
853|logarithm per cubic metre|log(m^-3)|log(m-3)||
854|per square metre|m^-2|m-2||
855|per metre per steradian|m^-2 sr^-1|m-2 sr-1||
856|volts per metre|V m^-1|V m-1||
857|per hour|h^-1|h-1||
858|square metre seconds per radian|m^2 s rad^-1|m2 s rad-1||
859|micro-moles per kilogram|umol kg^-1|umol kg-1||
860|nano sieverts per hour|nSv h^-1|nSv h-1||
861|metres per second per pascal|m s^-1 Pa^-1|m s-1 Pa-1||
862|metres per second per Kelvin|m s^-1 K^-1|m s-1 K-1||
863|moles per square centimetre|mol cm^-2|mol cm-2||
864|kilograms per litre|kg l^-1|kg l-1||
865|milligrams per cubic metre|mg m^-3|mg m-3||

### Comments

Occurence in Table B

Code figure|Abbreviation|Occurence
-|-|-
845|K-1|003024
846|K2|012190
847|log_(m2_m-2)|013100
848|log_(m3_m-2)|013101
849|kg_m-2_h-1|013114
850|K_K-1|013169
851|W_m-2_sr-1_um-1|014043
852|Cd_m-2|014056
853|log_(m-3)|015006, 015009, 015052, 015053, 015054
854|m-2|015012, 020129
855|m-1_sr-1|015063, 015065, 015066, 015073, 015074
856|V_m-1|020123
857|h-1|020126
858|m2_s_rad-1|022106
859|umol_kg-1|022188, 041003
860|nSv_h-1|024014
861|m_s-1_Pa-1|040032
862|m_s-1_K-1|040033
863|mol_cm-2|040061, 040062
864|kg_l-1|041002
865|mg_m-3|041004

Impact marked as low below as whilst new code table entries these do not impact on the coding of the data.

### Requestor(s)

@david-i-berry 

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C-6

### Expected impact of change

LOW

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.24and26.June.2024 notes:
the team reviewed the proposal;
