### ISSUE TITLE
new satellites and instrument from Japan (CCT5 and CCT8) 

### ISSUE THREAD

**Issue by amilan17** [wmo-im/CCT#203]
### Initial request

I would like to reuqest to amend the common code table in Manual on Codes vI.2 for the satellite indentifier and instruments as attached.
I hope it would be adopted to the next Fast Track this November.
Please kindly let me know if you need further information.

### Amendment details

In Common Code table C-5: Satellite identifier,

123 GCOM-C
142 GOSAT-GW

In Common Code table C-8: Satellite instruments,

  Code: 477
Agency: JAXA
Type: Imaging multi spectral radiometer (passive microwave)
short name: AMSR3
long name: Advanced Microwave Scanning Radiometer 3

### Requestor(s)

Masato FUJIMOTO, Japan Focal Point for Codes and Data Representation Matters

### Stakeholder(s)

Enter list of stakeholder(s).

### Publication(s)

Example: Manual on Codes (WMO-No. 306), Volume I.2, Common Code Table C5 and C8

### Expected impact of change

None

**Comment by amilan17** [comment]
https://github.com/wmo-im/CCT/wiki/Teleconference.2.July.2024 notes
@SimonElliottEUM will confirm by 12 July

**Comment by SimonElliottEUM** [comment]
@amilan17 @marijanacrepulja There have been no objections coming from the CGMS Task Group, so I consider these proposals for CCT C-5 and C-8 endorsed by them.

**Comment by amilan17** [comment]
> @amilan17 @marijanacrepulja There have been no objections coming from the CGMS Task Group, so I consider these proposals for CCT C-5 and C-8 endorsed by them.

Thanks!
