### ISSUE TITLE
Comments received on DRAFT AMENDMENTS TO THE MANUAL ON CODES, VOLUME I.2 (WMO-NO. 306) BY FAST-TRACK PROCEDURE 

### ISSUE THREAD

**Issue by chenxiaoxia2019** [wmo-im/CCT#21]
# Summary and purpose
_DRAFT AMENDMENTS TO THE MANUAL ON CODES, VOLUME I.2 (WMO-NO. 306) BY FAST-TRACK PROCEDURE_ has been sent out on 28 July, 2020. 

The focal points for codes and data representation matters are invited to review and comment by 29 September, 2020.

There are 9 proposals in _Part C – Common Features to Binary and Alphanumeric Codes_, from No.24 to No.32.

# Action proposed
Comments received will be recorded here.

# Document
[FT-2020-2-Vol I.2.pdf](https://github.com/wmo-im/CCT/files/4993671/FT-2020-2-Vol.I.2.pdf)

**Comment by amilan17** [comment]
All issues were approved by FT-2020-2.
