### ISSUE TITLE
Add new entry to Common Code Table C-5 to identify HY-2C satellite of China

### ISSUE THREAD

**Issue by Annie-FangZHAO** [wmo-im/CCT#26]
# Branch
https://github.com/wmo-im/CCT/tree/issue-26

# Summary and purpose
This document proposes a new entry to Common Code Tables C-5 to identify HY-2C satellite of China.

# Action proposed
The meeting is kindly invited to validate the proposed new entry to be included within the next update to the WMO Manual on Codes.

# Discussions
HY-2C is the second operational satellite of the marine dynamic environment monitoring network of China and was successfully launched on September 21, 2020. It is equipped with radar altimeter, microwave scatterometer, calibration radiometer, data collection system and ship automatic identification system, and could effectively obtain marine dynamic environment information such as sea breeze, ocean wave, sea temperature, etc. To encode the scatterometer product in BUFR, we’d like to request a new entry to Common Code Table C-5 to identify HY-2C.

# Detailed proposal
|Code figure for I6I6I6|Code figure for BUFR (Code table 0 01 007)|Code figure for GRIB Edition 2|    |
|:---:|:---:|:---:|:---:|
|504|504|504|Hai Yang 2C (HY-2C, SOA/NSOAS China)|

**Comment by SimonElliottEUM** [comment]
Thanks for organising this @Annie-FangZHAO . EUMETSAT fully support this proposal.

**Comment by Annie-FangZHAO** [comment]
@amilan17 I have checked the proposal. It looks fine. Please merge it into the validation branch. Thank you.

**Comment by amilan17** [comment]
@Annie-FangZHAO Please update this branch first: https://github.com/wmo-im/CCT/blob/issue-26/C05.csv.

**Comment by Annie-FangZHAO** [comment]
> @Annie-FangZHAO Please update this branch first: https://github.com/wmo-im/CCT/blob/issue-26/C05.csv.

@amilan17 It's done. Thank you.

**Comment by amilan17** [comment]
Thank you. it is issue-26 is now merged with validation branch.
