### ISSUE TITLE
Changes to Manual on Codes Introduction and General Provisions

### ISSUE THREAD

**Issue by efucile** [wmo-im/CCT#27]
As a consequence of WMO reform, we have new Constituent bodies and structures. Therefore several changes are needed to reflect the new structures in the General Provisions.
Some more changes are required to introduce WIGOS and the Earth System approach.
The Secretariat will produce an amended version of the Manual along these lines.

**Comment by amilan17** [comment]
closing this, because this is not the responsibility of the TT-TDCF.
