### ISSUE TITLE
Revise Publication to "Latest Version" Page on Community

### ISSUE THREAD

**Issue by amilan17** [wmo-im/CCT#29]
# Summary and purpose
I'd like to simplify what is published to Community, but I need to understand what is important to keep. 
[Current](https://community.wmo.int/activity-areas/wmo-codes/manual-codes/latest-version)
[Previous](https://community.wmo.int/activity-areas/wmo-codes/manual-codes/previous-versions/2020-05-06) 

# Discussions

1.  Remove docs/pdfs of different sections of the manual, because the details are published in the amendment documents which can be found: https://community.wmo.int/activity-areas/wis/wis-manuals.
2. remove non-operational - rely on GitHub instead
3. remove experimental - rely on GitHub instead
4. remove pre-operational (decision may be subject to policy)

**Comment by sebvi** [comment]
For us at ECMWF it is vital to have a pdf (or word but pdf is better) published at the same time and if possible with the change from previous version highlighted in red. We use mostly the pdf in our day to day work.

The txt/csv and the xml version are the machine oriented side of the publication and the pdf and/or word are the human oriented side of the publication.

**Comment by erget** [comment]
I agree with @sebvi that the PDFs should be complete for all sections of the manual, even though I am primarily a user of the machine-readable items.

**Comment by amilan17** [comment]
@sebvi @erget Thank you for your feedback. 

The final publication with all the recent fast-track amendments will not always be available at the same time that the amendments become 'operational' and this will never have the changes highlighted. 

Could you rely on the last version published and the PDF of amendments (that shows what's changed), instead? This is an example of what we currently have for FT-2020-2 Vol I.2 documents. 

*   [Amendment Doc](https://wmoomm.sharepoint.com/:b:/s/wmocpdb/EeJwJyCXbKtFlsg-76w-1vMB9kfL2ctv5oOqb1t0UcuBTA?e=Kmp3uL) 
*   [Last publication](https://library.wmo.int/doc_num.php?explnum_id=10310)

**Comment by erget** [comment]
@amilan17 this works for me, as the operational tables are the ones I tend to use as PDF.

**Comment by amilan17** [comment]
This is the page where I post links to all recent amendments: [https://community.wmo.int/activity-areas/wis/wis-manuals](https://community.wmo.int/activity-areas/wis/wis-manuals)

This is the page where I post links to the 'machine-readable codes': https://community.wmo.int/activity-areas/wmo-codes/manual-codes/latest-version
