### ISSUE TITLE
script to produce legacy machine readable formats

### ISSUE THREAD

**Issue by efucile** [wmo-im/CCT#5]
In this repository we have csv files used as master copy of the tables. We need to publish XML version of these files as already available from here https://community.wmo.int/activity-areas/wmo-codes/manual-codes/latest-version
We need a python script to convert the csv files to the legacy formats, including xml and the file names.
From the user point of view we want to provide continuity and the use of gitHub should not be seen by the users as disruptive. The next release is going to be in November and we need to have a conversion process ready for that release.

**Comment by efucile** [comment]
From @marianmajan-ibl :

Multiple options for csv to xml are listed on the page https://help.ubuntu.com/community/Converting%20CSV%20to%20XML, I usually need to convert only one-two files and in such case I use the online converter — https://www.convertcsv.com/csv-to-xml.htm — works well.

I have simply modified the script from the webpage above, it reads all csv files in the directory (not in subdirectories), converts all csv to xml, keeping the file name. In the previous Atsushi’s XML exports the root element was “dataroot”, I kept it the same and the element of each record was the file name, e.g. “BUFRCREX_33_0_0_CodeFlag_en”, I have also kept the record element as the file name. These are simply configurable. 

We can elaborate details and modify what is needed, It’s been a long time since I end my programming carrier :), but I can ask my colleagues to finish the script. 

The main current discrepancy is that Atsushi’s output files were merged, these are not (as it was discussed yesterday). This can be solved with the script, when we agree about details. 

You can compare the new xml export (on the left) and Atsushi’s on the right:



The new one is also missing <No> element but that is easy to add, if needed. Also there are more elements (CSV table rows) in the new export. These discrepancies should not cause problems when using xml file, but we can test it widely later. 

To conclude it, if you want to create xml in the whole git main directory, you can do something like (on Linux / Mac, for Windows the script may needed to be modified):
 ~/BUFR4-master $ python ~/bin/csv2xml.py

In the example above the BUFR4-master repository is cloned to your home directory and script is stored in the bin subdirectory of your home directory… 

I am attaching a zip file with the script, one csv file and its xml export and Atsushi’s xml file.

Of course you can use it for GRIB tables in the same way.

**Comment by erget** [comment]
EUMETSAT can also both import and export in the WMO XML and CSV formats. So if we continue to produce CSV I can use our Vocabulary Manager's REST API to produce the XML on demand.

**Comment by efucile** [comment]
Given that the conversion is a simple task I would prefer to have a python in the repository so that we can run it in the release phase. It can also be useful in the validation step because some of the centres are consuming XML not csv and to validate they need to get the XML. Actually we could have a github actions or ci-travis producing the XML from the csv in the repository. This would give us the advantage that the release from gitHub can be identical to the current release on the web which is not the case now.

**Comment by marianmajan-ibl** [comment]
Enrico, would you like me to commit the script somewhere?

**Comment by efucile** [comment]
Yes Marian, 
please push the script in this branch [csv-to-xml](https://github.com/wmo-im/CCT/tree/csv-to-xml) that we are going to use as feature branch for this issue.

**Comment by marianmajan-ibl** [comment]
Committed. We should discuss the other requirements (merging of tables to one file?), but this can be done anytime later.

**Comment by efucile** [comment]
I agree can be done later. However, the requirement is to produce exactly what we have now on the web. 
A good test for the script could be to produce the content of this directory [fromWeb/Common_20200506](https://github.com/wmo-im/CCT/tree/master/fromWeb/Common_20200506) from the current csv files in the repo. This should be done for all the other repositories BUFR4 and GRIB2. I would start from this one and make similar issues in the other repositories when we are ready with this. I don't expect a big difference with BUFR and GRIB.

**Comment by efucile** [comment]
@marianmajan-ibl @erget @tomkralidis 
we have now a workflow on this branch https://github.com/wmo-im/CCT/blob/csv-to-xml/.github/workflows/main.yml 
At every push or pull_request it is re-creating all the xml files and pushing them in the same branch. This should be enough to keep the xml files aligned with the csv version.
Can you please have a look? If this is ok we can do the same in GRIB and BUFR where we also need to cat all the csv files in one single before creating the xml. Do we need the xsd files?
I think that they are created by the access database of Atsushi, but they are not needed by the user.

**Comment by efucile** [comment]
@erget @marianmajan-ibl @tomkralidis 
just to mention that the script has a little problem. It fails if the change is not on the tables. This is because the git push after the creation of xml files fails because there is no change.
Not sure how to solve, but it's not a blocking issue.

**Comment by tomkralidis** [comment]
I've made some minimal changes in #15 . Other comments for consideration:

- unless anyone is using these XML files with a validating XML parser, the XSD's might be overkill?
- is the output XML format fixed/legacy?  Is there opportunity to improve it?
- should we consider JSON as an additional option?
- should we be creating the XML files on every commit or every official release?

**Comment by efucile** [comment]
Thanks @tomkralidis I am trying to answer your questions.
- I think that xsd is not needed in this context. We'll try to release without xsd.
- we should consider it as fixed legacy
- agree that a json format could be useful. Do we have a requirement? Who is going to use it?
- I think that we need at every commit because we want to give people to test the tables at any time of the development. Release time is too late for testing.

**Comment by tomkralidis** [comment]
Thanks @efucile and +1 to your comments.  RE: JSON: no requirement, but perhaps an opportunity for some point in the future.

**Comment by erget** [comment]
The XSDs are definitely overkill because they define the same schema but with a different name for each table version and therefore can't be re-used.

Agree that the full set of assets should be produced in the next-release branch for testing at all times.

Also agree thta JSON would be useful, but we've survived without it thus far so we might consider it an enhancement. Incidentally, in the Vocabulary Manager we're using JSON as an internal storage format for the tables already.
