### ISSUE TITLE
Add new entry to Common Code Table C-5 to identify Nimbus-1 and Nimbus-2 satellite

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#50]
# Branch
https://github.com/wmo-im/CCT/tree/issue50

# Summary and purpose

ECMWF proposes a new entry to Common Code Tables C-5 to identify NIMBUS 1 and NIMBUS 2 satellites.

# Action proposed

The team is kindly asked to validate the proposed new entries to be included within the next update to the WMO Manual on Codes.

# Discussions

ECMWF is preparing for ERA6 and need to pre-process and assimilate "rescued" satellite data from NIMBUS 1 and NIMBUS 2. Therefore needed satellite identifiers are proposed. 

# Detailed proposal

|Code figure for I6I6I6|Code figure for BUFR (Code table 0 01 007)|Code figure for GRIB Edition 2|    |
|:---:|:---:|:---:|:---:|
|761|761|761|NIMBUS 1|
|762|762|762|NIMBUS 2|

**Comment by marijanacrepulja** [comment]
Hello @jitsukoh, I have updated the issue50 branch.

**Comment by jitsukoh** [comment]
@marijanacrepulja @amilan17 I confirm that this proposal is finalized and the branch is updated, and move this issue to "Validated" status.
