### ISSUE TITLE
Add new entries to Common Code Table C-8 to identify rescued data from Spascia

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#51]
# Branch

https://github.com/wmo-im/CCT/tree/issue51

# Summary and purpose

ECMWF proposes a new entry to Common Code Tables C-8 to identify data from rescued satellite instruments.

# Action proposed

The team is kindly asked to validate the proposed new entries to be included within the next update to the WMO Manual on Codes.

# Discussions

ECMWF is preparing for ERA6 and need to pre-process and assimilate "rescued" satellite data from MRIR, PMR, HRIR, SIRS, IRIS, THIR, SMMR, VTPR satellite instruments.

# Detailed proposal

Add the following elements to Common Code Table C8 Satellite instruments:  
| Code | Agency | Type | Instrument short name | Instrument long name |  
| --- | --- | --- | --- | --- |  
| 397 | NASA | Radiometer | HRIR | High Resolution Infrared Radiometer  
| 398 | NASA | Radiometer | MRIR | Single-channel IR radiometer |  
| 14 | UKSA | Radiometer | PMR| Pressure Modulator Radiometer |  
| 990 | NASA | Radiometer | SMMR | Scanning Multichannel Microwave Radiometer |  
| 991| NASA | Radiometer | THIR| Temperature-Humidity Infrared Radiometer |  
| 909 | NOAA | Radiometer | VTPR | Vertical Temperature Profile Radiometer |  
| 421 | NASA | Spectrometer | SIRS-A | Satellite Infra-Red Spectrometer - A |  
| 422 | NASA | Spectrometer | SIRS-B | Satellite Infra-Red Spectrometer - B |

**Comment by amilan17** [comment]
@SimonElliottEUM will cross check with the CGMS Task Force

**Comment by SimonElliottEUM** [comment]
CGMS Task Force consulted and given until 3 May to raise any objections

**Comment by SimonElliottEUM** [comment]
CGMS considered this and did not raise any objections. So this can be considered endorsed by CGMS TFSDC

**Comment by marijanacrepulja** [comment]
Hello @jitsukoh, I have updated the issue51 branch.

**Comment by jitsukoh** [comment]
@marijanacrepulja @amilan17 I confirm that this proposal is finalized and the branch is updated, and move this issue to "Validated" status.
