### ISSUE TITLE
Add new entry in Common Code Table C12 to identify Saint-Denis (Réunion) as a sub-centre for Lannion (France)

### ISSUE THREAD

**Issue by yg31** [wmo-im/CCT#52]
# Branch
https://github.com/wmo-im/CCT/tree/issue52

# Summary and purpose

Addition of a new entry in Common Code Table C-12 to properly identify satellite data received at Saint-Denis (La Réunion), encoded in BUFR at Lannion (France) and disseminated by EUMETSAT.

# Action proposed

The team is kindly asked to validate the proposed new entriy to be included within the next update to the WMO Manual on Codes.

# Discussions

Within the EARS network (EUMETSAT Advanced Retransmission Service), satellite data is received at Saint-Denis (La Réunion), encoded at Lannion (France) and transmitted to EUMETSAT, who disseminate it to other users.
Since this data is encoded by Meteo-France: identifying it as produced by EUMETSAT (sub-centre Saint-Denis) appear inadequate.
Saint-Denis is already referenced in Common Code Table C-1 (figure 25) but this centre has no responsibility in encoding satellite data received locally.
The last considered solution is to identify this data using production center Lannion (C-1 figure: 211, Region VI) with sub-centre Saint-Denis (new figure in C-12).

# Detailed proposal

ADD in Common Code Table C-12, region VI:

Code 			figure | Name | Code 			figure | Name
-- | -- | -- | --
211| Lannion | 10 | Saint-Denis (La Reunion)

**Comment by amilan17** [comment]
per meeting discussion: will be confirmed if it is ok to drop the accent, in validation, branch will be created

**Comment by amilan17** [comment]
related to ISSUE: wmo-im/BUFR4#55

**Comment by amilan17** [comment]
DECISION: update branch without the accent

**Comment by jitsukoh** [comment]
@amilan17 can you update the branch according to the decision yesterday?

**Comment by amilan17** [comment]
done. @jitsukoh

**Comment by jitsukoh** [comment]
@amilan17 thank you. I confirm that the proposal is finalized, branch is updated and I move this issue to validated status.
