### ISSUE TITLE
New data category for Lidar (ground based) in Common Code Table C–13

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#53]
# Branch

https://github.com/wmo-im/CCT/tree/issue53

# Summary and purpose

ECMWF proposes new entry to the Common Code Tables C-13 in order to represent Lidar ground based observations.

# Action proposed

The meeting is kindly asked to approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

ECMWF is preparing for monitoring and assimilation of ground based lidar data. To aid better identification of the data new data category is needed.

# Detailed proposal

Add the new code 0 under 32 Lidar (Ground based) in COMMON CODE TABLE C–13: Data sub-categories of categories defined by entries in BUFR Table A

| DATA CATEGORIES  |     |  INTERNATIONAL DATA SUB-CATEGORIES|      |  
| ------------- | -------------| -------------| -------------|     
| Code figure  | Name  |  Code figure | Name|
| 32  | Lidar (ground based)  |  0  |  Wind, Cloud, Aerosol |

**Comment by amilan17** [comment]
per discussion in meeting: C13 is for listing sub-categories listed in BUFR Table A. 

In Table A: 

<table><tbody><tr><td>23</td><td>Lidar (satellite)</td></tr></tbody></table>

Marijana will update with sub-categories

**Comment by marijanacrepulja** [comment]
Hello @jitsukoh  I have updated the issue53 branch.

**Comment by jitsukoh** [comment]
@marijanacrepulja thank you for updating the branch. If I understand correctly, this proposal consists of two parts: to add new entry 32 Lidar (ground based) in [BUFR table A](https://github.com/wmo-im/BUFR4/blob/master/BUFR_TableA_en.csv) and then, to add a new entry 0 Wind, cloud, aerosol under the new sub-category 32 in C-13, so I think the change included in this branch is not enough and we also need to make a change in BUFR table A. I need @amilan17 's instruction here; do we need to create a new issue and a new branch in the BUFR repository to deal with this?? 

Probably the final proposal in the original post needs to be clarified in this regard, something like 
Add the new code 32 Lidar (Ground based) in BUFR table A and add the new code 0 under 32 Lidar (Ground based) in COMMON CODE TABLE C–13: Data sub-categories of categories defined by entries in BUFR Table A

**Comment by amilan17** [comment]
if Table A needs to also be modified, then create a new issue in the BUFR repository and I will create a branch to edit.

**Comment by marijanacrepulja** [comment]
@jitsukoh thank you for your comments, I have updated the original post with suggested wording and created new issue under BUFR repository for updating BUFR table A with the new data category.

**Comment by jitsukoh** [comment]
@amilan17 can you provide the difference between this branch and the master? I will check it and move this issue to validated...

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/compare/master...issue53](https://github.com/wmo-im/CCT/compare/master...issue53)

**Comment by jitsukoh** [comment]
@marijanacrepulja @amilan17 it seems there are no spaces between words in "Wind,Cloud,Aerosol". Is it correct?

**Comment by marijanacrepulja** [comment]
@jitsukoh I have updated the issue53 branch by adding the spaces between words in "Wind, Cloud, Aerosol".

**Comment by jitsukoh** [comment]
@marijanacrepulja thank you for updating the branch. I confirm that this proposal is finalized and the branch is updated, and move to validated status.
