### ISSUE TITLE
CCT 14: new chemical constituents/aerosols 

### ISSUE THREAD

**Issue by sebvi** [wmo-im/CCT#55]
# Branch

https://github.com/wmo-im/CCT/tree/issue55

# Summary and purpose

# Action proposed
The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions
ECMWF is proposing to include 2 new entries in common code table 14: 

- Anthropogenic volatile organic compounds
- biomass burning volatile organic compounds

These 2 new entries differs from the existing entries 60013-60015 which specifically excludes methane.

# Detailed proposal

add in common code table 14
| Code | Meaning | Formula |
|--|--|--|
| 60033 | Anthropogenic volatile organic compounds | aVOC |
| 60034 | Biomass burning volatile organic compounds | bbVOC |

**Comment by sebvi** [comment]
branch updated

**Comment by jitsukoh** [comment]
@sebvi @amilan17 I confirm that this proposal is finalized and the branch is updated, and move this issue to "Validated" status.
