### ISSUE TITLE
new entry in CCT-13 for marine surface drones

### ISSUE THREAD

**Issue by jbathegit** [wmo-im/CCT#57]
# Branch
https://github.com/wmo-im/CCT/tree/issue57

# Summary and purpose
 
A new entry in CCT-13 is proposed for use with uncrewed marine surface drones.

# Discussions

Increasing use is being made of uncrewed drones for marine surface and subsurface observations.  These are platforms that can be actively remote-controlled by a human or even pre-programmed to maneuver themselves along a certain route once deployed, as opposed to unmoored buoys which are basically at the mercy of wind and sea currents for their movement.

An example of this type of platform has been manufactured by [Saildrone Inc.](https://www.saildrone.com/) who have begun sharing some of their observed data in BUFR for potential use in NWP.  However, within CCT-13, none of the existing data subcategories for data category 1 (="Surface data - sea") seems appropriate for describing this particular type of platform.

# Detailed proposal

Add the following new entry to CCT-13:

Data Category  |   Meaning |  Data Subcategory |  Meaning
:-----------------: |  ----------- |  :----------------:  | -----------
  1  |   Surface data - sea |   15  |  Uncrewed surface vehicle

**Comment by jbathegit** [comment]
Hello @wmo-im/tt-tdcf, I'd like to propose this short item for discussion/consideration as part of FT-2021-2.

I would welcome alternative suggestions for the meaning of the proposed new subcategory, if anyone has any better ideas based on the details provided within the URL of the example in the main discussion.

**Comment by SimonElliottEUM** [comment]
@jbathegit I don't think you need to say "Uncrewed" and "drone". I would either say "Uncrewed surface vehicle" or "Surface drone".

**Comment by jbathegit** [comment]
Thanks @SimonElliottEUM for the feedback.  Out of those two suggestions, my preference would be the first one, so I've gone ahead and updated the proposal accordingly.

**Comment by SimonElliottEUM** [comment]
@jbathegit 👍

**Comment by jbathegit** [comment]
The TT-TDCF agreed to this proposal during our 19 May 2021 plenary discussions.

**Comment by jbathegit** [comment]
Hello @amilan17 and @jitsukoh, I have now updated the `issue57` branch with the above proposal, as agreed during our plenary discussions.

**Comment by jitsukoh** [comment]
@jbathegit @amilan17 I confirm that this proposal is finalized and the branch is updated, and move this issue to "Validated" status.
