### ISSUE TITLE
New entries needed in Common Code Table C-5 for EUMETSAT satellites

### ISSUE THREAD

**Issue by SimonElliottEUM** [wmo-im/CCT#68]
# Branch
https://github.com/wmo-im/CCT/tree/issue68
# Summary and purpose

The naming convention for EUMETSAT's next generation of geostationary (MTG) and polar (Metop-SG) satellites has been confirmed and needs to be captured in Common Code Table C-5

# Action proposed

Add entries to common code table C-5

# Discussions

The number of next generation satellites is well know and fixed. The naming convention has been confirmed in the first half of 2021. The entries need to be allocated in Common Code Table C-5 to ensure consistency in identification.

# Detailed proposal

Noting that in Common Code Table C-5, "_001–099: Numbers allocated to Europe_" and "_EVEN DECILES INDICATE POLAR-ORBITING SATELLITES AND ODD DECILES INDICATE GEOSTATIONARY SATELLITES_", the following entries are requested:

Metop-D → 24
Metop-E → 25
Metop-F → 26
Metop-G → 27
Metop-H → 28
Metop-I → 29
There will be 3 Metop-SG-A satellites and 3 Metop-SG-B satellites. They will be named Metop-D to Metop-I in the order they are brought into service.

METEOSAT 12 → 71
METEOSAT 13 → 72
METEOSAT 14 → 73
METEOSAT 15 → 74
METEOSAT 16 → 75
METEOSAT 17 → 76
There will be 4 MTG-I satellites and 2 MTG-S satellites. They will be named METEOSAT-12 to METEOSAT-17 in the order they are brought into service.

**Comment by SimonElliottEUM** [comment]
@jitsukoh @amilan17 This branch is ready for the next step

**Comment by amilan17** [comment]
@SimonElliottEUM can you please update the branch with your proposal?

**Comment by SimonElliottEUM** [comment]
@jitsukoh @amilan17 This branch is now really ready for the next step. I have updated the CSV file accordingly

**Comment by jitsukoh** [comment]
@SimonElliottEUM @amilan17  I confirm that the branch is updated and this issue was moved to the validated status.

**Comment by marijanacrepulja** [comment]
Hi @SimonElliottEUM and @amilan17 
I would like to consult with you about the satellite names, as there is inconsistency between Common Code Tables and WMO OSCAR.

eg.METEOSAT 12 vs MTGI1

Should names in WMO OSCAR follow the definitions from CCT 05?

Many thanks!

**Comment by SimonElliottEUM** [comment]
Hi @amilan17  Common Code Table C-5 is the correct one. I have carefully consulted and controlled what we added there - the names were subject to formal approval from our side. I have no control of what get's put in WMO OSCAR. There is a longstanding initiative to link the contents of OSCAR to CCT-C5 and CCT-C8 for the satellite data. @hpohjolawmo is taking care of this.
