### ISSUE TITLE
Add a new entry to Common Code Tables C-11 to identify IAP

### ISSUE THREAD

**Issue by Annie-FangZHAO** [wmo-im/CCT#7]
### **Summary and purpose**
This document proposes a new entry to Common Code Tables C-11 to identify the Institute of Atmospheric Physics (IAP) of Chinese Academy of Sciences (CAS).
### **Action proposed**
The meeting is kindly invited to review the proposed new entry and approve it for pre-operational use and inclusion within the next update to the WMO Manual on Codes.
### **Discussions**
The Institute of Atmospheric Physics (IAP) of Chinese Academy of Sciences (CAS) would like to contribute to WCRP-WWRP-THORPEX S2S Project. A ensemble prediction system, named FGOALS-f2, has been carried out to achieve 20-year hindcast and started the real-time prediction since June 2019. In order to represent the products in GRIB 2, we’d like to request a new entry to Common Code Tables C-11 to identify IAP.
### **Detailed proposal**
Add a new entry to Common Code Tables C-11
00291                 291	           The Institute of Atmospheric Physics(IAP) of Chinese Academy of                                       Sciences (CAS)

**Comment by Annie-FangZHAO** [comment]
Dear @efucile 
I moved this proposal by mistake to “Submitted” this morning, could you please kinedly move it back to “In validation”. Thank you very much.
Bye the way, for the milestone, could we seprate pre-operational use from FT-2020-2?

**Comment by Annie-FangZHAO** [comment]
@chenxiaoxia2019 @efucile @jitsukoh 
I reviewed the new entry to C-11 in the FT2020-2 branch for CCT. It looks fine. Thank you.

**Comment by amilan17** [comment]
SUMMARY: Add entry to Common Code Table C-11.

**Comment by amilan17** [comment]
Approved by FT-2020-2.
