### ISSUE TITLE
New new entry in CCT C-2 for Meteosis radiosonde system

### ISSUE THREAD

**Issue by amilan17** [wmo-im/CCT#71]
# Branch
https://github.com/wmo-im/CCT/tree/issue71
# Summary and purpose

The Observation Systems Department of Turkish State Meteorological Service (TSMS) has completed test flights, approved the Meteosis' radiosonde system and need a new code in Table C-2 for their radiosonde system.

# Detailed proposal 

| **Date of assignment** | **Code figure for rara** | **Code figure for BUFR** | **RadiosondeSoundingSystemUsed\_en** |
| --- | --- | --- | --- |
| xx/5/2022  |  65 | 165  | Meteosis MTS-01 (Turkey) |

**Comment by jitsukoh** [comment]
@amilan17 here is the additional information provided by Yasin. Could you find a code figure available for this?
1) The system's name is "Meteosis MTS-01"
2) The system supports both TAC and BUFR formats.

**Comment by amilan17** [comment]
@jitsukoh branch is updated. Does the date of assignment correspond with the FT release date?

**Comment by jitsukoh** [comment]
@amilan17 my apologies, the system name should include a country name, so I updated the proposal to "Meteosis MTS-01 (Turkey)". Can you update the branch accordingly?
I assume that the date should be the Effective date of the master table version number defined by C-0.
