### ISSUE TITLE
Proposal for new entry in Common Code Tables C5

### ISSUE THREAD

**Issue by erget** [wmo-im/CCT#8]
# Summary and purpose
This document proposes a new entry to Common Code Tables C5 in order to multiple Sentinel-3 satellites.

# Action proposed
The meeting is requested to approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions
EUMETSAT will produce atmospheric motion vectors using data from the SLSTR instrument (Sea and land surface temperature radiometer) on multiple Sentinel-3 satellites (initially Sentinel-3 A and Sentinel-3 B).

In order to be able to represent a combination of Sentinel-3 satellites, a new entry in Common Code Table C-5 is required. This entry must be in the  range  from  850  to  869  as this is to be  used  to  indicate  combinations  of satellites.

# Detailed proposal
Add the following elements to Common Code Table C5 Satellite identifier:

| Code figure for I<sub>6</sub>I<sub>6</sub>I<sub>6</sub> | Code   figure for BUFR (Code table 0 01 007) | Code   figure for GRIB Edition 2 |  Meaning |
-- | -- | -- | --
| 856 | 856 | 856 | Combination   of Sentinel-3 satellites

**Comment by erget** [comment]
@chenxiaoxia2019 I see the "has branch" label but am unable to find the branch - can you point me in the right direction? Thanks very much!

**Comment by amilan17** [comment]
SUMMARY: Add entry to Common Code Tables C-5.

**Comment by amilan17** [comment]
Approved by FT-2020-2.
