### ISSUE TITLE
Add new data designators T1T2 to Manual on the GTS (WMO-No.386) Attachment II-5

### ISSUE THREAD

**Issue by chenxiaoxia2019** [wmo-im/CCT#83]
# Summary and purpose

To add new headers in Manual on the GTS

# Action proposed

To update the Data Designators T1T2 in _[Attachment II-5](https://library.wmo.int/doc_num.php?explnum_id=10469#page=100)_ on **_Manual on the Global Telecommunication System (WMO-No.386)_**.

# Discussions

- _Basic Information_: Manual on the GTS: 2015 edition, updated in 2020

- _Requirement_: Request from DWD to announce Meteosat-9 Data Available via WIS/GTS on ([WIS Operational Newsletter](https://community.wmo.int/news/operational-newsletter)) 

> EUMETSAT to provide Meteosat-9 data using IW[FR][CGK]ii EUMG.  
> 
> _The IWF[CGK]ii EUMG bulletins are all-sky radiance data from the parallel dissemination stream
> The IWR[CGK]ii EUMG bulletins are clear sky radiance data from the parallel dissemination stream_
> 
> _It is planned to be using these headers from 09/05/2022 until 30/06/2022._

- _Problems_: 

Based on the _**Manual on the GTS**_, there is no header IW. 

- _Progress:_

After confirmation with EUMETSAT, there are some new headers used by EUMETSAT since 2016 which haven't been updated in the Manual on the GTS.

# Detailed proposal

To update [Table B3](https://library.wmo.int/doc_num.php?explnum_id=10469#page=106) for satellite data

Designator| Data type
-- | -- 
E |all EUMETSAT global data from Metop satellites
W |parallel dissemination of data from geostationary satellites
R | EUMETSAT data from Meteosat Rapid Scanning service

- **To be discussed**: 

_For the current data type description, do we update from the general one to the specific EUMETSAT one?_
> Currently, from EUMETSAT, they use 
> T1T2 = “IS” for Sentinel-3, Sentinel-6, SARAL and JASON-3 altimetry data
> T1T2 = “IU” for EUMETSAT data from Meteosat 0-degree prime mission
> T1T2 = “IX” for EUMETSAT data from Indian Ocean Data Coverage service

In Manual on the GTS, it is more general in this way: 
Designator| Data type
-- | -- 
S| Surface/sea level
U| Upper-air data
X| Other data types

**Comment by chenxiaoxia2019** [comment]
@SimonElliottEUM Hi, Simon, I added the issue for Manual on the GTS fast track. Could you please help comment on this? Much appreciated.

**Comment by amilan17** [comment]
@SimonElliottEUM WMO is no longer updating the Manual on GTS, therefore, we cannot add this to the publication

**Comment by SimonElliottEUM** [comment]
@chenxiaoxia2019 @amilan17 How will WMO handle cases where new letters need to be assigned in the tables in the Manual on the GTS without updating the Manual? I understand that if the WIS 2.0 plans are agreed at the end of the year (I really hope they are!) then there will be no new headers etc from 2024. But what about the next 18 months - it cannot be that there are no more changes for that period - we would have needed far more warning to grab all the new entries we need in the tables prior to the hoped for roll out of WIS 2.0. Please clarify what is going on. Thanks.
