### ISSUE TITLE
CCT C-2 Korean equipment code for WeatheX WxR-301D

### ISSUE THREAD

**Issue by amilan17** [wmo-im/CCT#85]
# Summary and purpose

Initial request by: Heo Boram, KMA's National Focal Point for Codes and Data Representation Matters.

  _I would like to add a new Korean equipment code to ATTACHMENT I's COMMON CODE TABLE C-2 (Radiosonde/sound system used) as follows._

_Date of assignment of number:  21/03/2022_  
_Code figure for rara : 34_  
_Code figure for BUFR: 134_  
_Equipment Name (Country Name) : WEATHEX WxR-301D with derived pressure from GPS (Republic of Korea)_

_Could you please consider whether the following code can be added to Vol.I.1. ?_

_Please let me know if you need any information for this._

# Action proposed

Enter text.

# Discussions

Requirements and purposes of the proposal along with other background information, which could be included in the SUMMARY OF MEETING REPORT.

# Detailed proposal

_Date of assignment of number:  21/03/2022_  
_Code figure for rara : 38_  
_Code figure for BUFR: 138_  
_Equipment Name (Country Name) : WEATHEX WxR-301D with derived pressure from GPS (Republic of Korea)_

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-18-and-19.5.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-18-and-19.5.2022) notes:

@marijanacrepulja update branch

**Comment by amilan17** [comment]
these codes are already in use for different equipment

<table><tbody><tr><td>06/05/2020</td><td>34</td><td>134</td><td>iMet-4 GPS radiosonde (USA)</td></tr></tbody></table>

**Comment by marijanacrepulja** [comment]
@amilan17 branch is updated. I have moved the issue to validated.
