### ISSUE TITLE
Correct typo in CCT 08

### ISSUE THREAD

**Issue by amilan17** [wmo-im/CCT#87]
# Branch

\[add when created\]

# Summary and purpose

Acronym and long name do not match. 

<table><tbody><tr><td>398</td><td>NASA</td><td>Radiometer</td><td>MRIR</td><td>Single channel IR radiometer</td></tr></tbody></table>

This code was recently introduced in Issue #51. 

---

# Detailed proposal

<table><tbody><tr><td>398</td><td>NASA</td><td>Radiometer</td><td>MRIR</td><td>Medium Resolution Infrared Radiometer</td></tr></tbody></table>

**Comment by SimonElliottEUM** [comment]
I am sure MRIR is the right acronym and the instrument is as described in WMO Oscar Space: "5-channel radiometer, two broad-band (0.2-4.0 μm and 5-30 μm), three narrow-band (6.4-6.9 μm, 10-11 μm and 14-16 μm). On Nimbus-3 the 5-30 μm channel was replaced by 20-23 μm". But we should let @marijanacrepulja confirm that with the source of the recovered data.

**Comment by marijanacrepulja** [comment]
@amilan17 Thank you for spotting the typo. I have confirmed with my colleague and the long name should be corrected.
Medium Resolution Infrared Radiometer is the correct name as it is defined in WMO Oscar.

**Comment by amilan17** [comment]
I included this typo fix in the FT2022-1 branch.
