### ISSUE TITLE
Add new entry to C-5 to identify ALTIUS, EarthCARE and TROPICS

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#88]
# Summary and purpose

ECMWF proposes a new entries to Common Code Tables C-5.

# Action proposed

The team is kindly asked to validate the proposed new entries to be included within the next update to the WMO Manual on Codes.

# Discussions

ECMWF is preparing to pre-process and assimilate observations from ALTIUS, EarthCARE and TROPICS. Therefore needed satellite identifiers are proposed.

# Detailed proposal

|Code figure for I6I6I6|Code figure for BUFR (Code table 0 01 007)|Code figure for GRIB Edition 2|    |
|:---:|:---:|:---:|:---:|
|45|45|45|ALTIUS|
|49|49|49|EarthCARE|
|709|709|709| TROPICS-01 (Pathfinder)| 
|227|227|227| TROPICS-02 | 
|228|228|228| TROPICS-03 | 
|229|229|229| TROPICS-04 | 
|263|263|263| TROPICS-05 | 
|264|264|264| TROPICS-06 | 
|284|284|284| TROPICS-07 |

**Comment by SimonElliottEUM** [comment]
@marijanacrepulja TROPICS is in a low earth orbit and so needs an even decile. Perhaps you could consider proposing 227-229 and 263-266, or something similar

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM many thanks for your comment, I have updated the issue. Could you please pass the proposals to the CGMS Task Group for comments

**Comment by SimonElliottEUM** [comment]
@marijanacrepulja I have passed the updated proposal to the CGMS Task Group, and given them until the end of May to comment.

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-18-and-19.5.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-18-and-19.5.2022) notes:

waiting for feedback

**Comment by marijanacrepulja** [comment]
@amilan17 I have updated branch, please review and move to "Ready to FT"

**Comment by SimonElliottEUM** [comment]
These entries looks fine to me now.

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM, @hpohjolawmo, @amilan17 
  
Looking at other satellite names, it seems there is no consistency. As for the TROPICS there is the extra zero in the name (e.g TROPICS-02 instead TROPICS-2), also the use of hyphen, some satellite names have a hyphen 
(eg Metop-1), some don't (NOAA 20). Do we want to use extra zero in name for TROPICS?

**Comment by SimonElliottEUM** [comment]
@hpohjolawmo @amilan17 @marijanacrepulja there is no consistency - but none is needed. Each agency makes there own very specific naming conventions. Frankly, as there is no ambiguity, I would leave it up to the agencies to make their own decisions concerning the names.

**Comment by marijanacrepulja** [comment]
@SimonElliottEUM I am happy with this :+1:
