### ISSUE TITLE
New sub-category for Mode-S in C-13

### ISSUE THREAD

**Issue by marijanacrepulja** [wmo-im/CCT#9]
# Summary and purpose
 ECMWF proposes new entry to Common Code Tables C-13 in order to represent Mode-S aircraft data.

# Action proposed
The meeting is kindly asked to approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions
ECMWF is working on processing Mode-S reports. The data are available in BUFR AMDAR v7 format for time being. In order to allow the unambiguous representation of aircraft data from Mode-S, additional entry is required in Common Code Table C-13. This is in preparation for development of dedicated BUFR template to standardize encoding of these data.

# Detailed proposal
Add the new code **2 - Mode-S**
COMMON CODE TABLE C–13: Data sub-categories of categories defined by entries in BUFR Table A

| DATA CATEGORIES  |     |  INTERNATIONAL DATA SUB-CATEGORIES|      |  
| ------------- | -------------| -------------| -------------|     
| Code figure  | Name  |  Code figure | Name|
| 4  | Single level upper-air data (other than satellite)  |  0   | ASDAR/ACARS (AMDAR)  |
|   |  |  1   | Manual (AIREP, PIREP)  |
|   |  |  **2**   |  **Mode-S** |

**Comment by marijanacrepulja** [comment]
@chenxiaoxia2019 , @efucile , @jitsukoh

I reviewed the new C-13 entry in the FT2020-2 branch for CCT. It looks fine.

**Comment by amilan17** [comment]
Add entry to Common Code Table C-13.

**Comment by amilan17** [comment]
Approved by FT-2020-2.
