### ISSUE TITLE
Common Code Table C-14: new H2O entries 

### ISSUE THREAD

**Issue by sebvi** [wmo-im/CCT#92]
# Summary and purpose

ECMWF is requesting new entries to characterize specific subset of water as a chemical constituent

# Action proposed

The team is kindly asked to review and approve the contents for inclusion within the next update to the WMO Manual on Codes.

# Discussions

In order to produce pH of rain and cloud water (acidity of rain/cloud), ECMWF is requesting 2 new entries to spatially qualify which type of water is considered. These new entries will be used together with the pH entry requested in GRIB2 https://github.com/wmo-im/GRIB2/issues/151  

# Detailed proposal

add in Common Code Table C-14

| Code | Meaning | Formula |
|--|--|--|
| 62034 | Rain water | H2Orain |
| 62035 | Cloud water | H2Ocloud |

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-18-and-19.5.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-18-and-19.5.2022) notes:

use two entries after entries in #91

**Comment by amilan17** [comment]
[https://github.com/wmo-im/CCT/wiki/Teleconference-8.6.2022](https://github.com/wmo-im/CCT/wiki/Teleconference-8.6.2022) notes: 

@sebvi update branch and notify Marijana when ready

**Comment by amilan17** [comment]
@marijanacrepulja - I checked this branch and moved it to directly to ready for FT column
